# Generated by Django 3.1.4 on 2021-03-10 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='last_name')),
                ('age', models.IntegerField(null=True, verbose_name='age')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=50, verbose_name='gender')),
                ('nationality', models.CharField(max_length=50, null=True, verbose_name='nationality')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('fax_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('state', models.CharField(max_length=50, null=True, verbose_name='state')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='city')),
                ('zip_code', models.CharField(max_length=50, null=True, verbose_name='zip code')),
                ('street_address', models.CharField(max_length=70, null=True, verbose_name='Street address')),
                ('pass_port_copy', models.ImageField(null=True, upload_to='passports', verbose_name='passport image')),
                ('selfie_proof', models.ImageField(null=True, upload_to='selfies_proof', verbose_name='profile photo')),
                ('wallet_address', models.CharField(max_length=50, null=True, verbose_name='wallet address')),
                ('card', models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('Prepaid', 'Prepaid')], max_length=50, null=True, verbose_name='card')),
                ('kyc_approve', models.CharField(choices=[('Approved', 'Approved'), ('Cancel', 'cancel')], max_length=50, null=True, verbose_name='kyc approve')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
