# Generated by Django 3.1.4 on 2021-03-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycmodel',
            old_name='fax_number',
            new_name='phone_number',
        ),
    ]
