# Generated by Django 3.1.4 on 2021-03-10 13:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_auto_20210310_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
