# Generated by Django 3.1.4 on 2021-03-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_auto_20210310_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycmodel',
            name='wallet_balance',
            field=models.PositiveIntegerField(blank=True, default=23, verbose_name='wallet balance when user applied for kyc form'),
            preserve_default=False,
        ),
    ]
