# Generated by Django 3.1.4 on 2021-03-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_kycmodel_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='wallet_balance',
            field=models.CharField(blank=True, max_length=150, verbose_name='wallet balance when user applied for kyc form'),
        ),
    ]
